title:  "Richard's Blog"
tagline: "tech ,life"
description:

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'richards-blog-1'

menu:
- {name: 'Documents', folder: 'pages', file: 'documents.html'}
- {name: 'Golang', folder: 'pages', file: 'golang.html'}
- {name: 'Travel', folder: 'pages', file: 'travel.html'}
- {name: 'MachineLearning', folder: 'pages', file: 'ml.html'}

social:
- {icon: 'facebook', link: 'https://www.facebook.com/Richard.Richard.Richard.Richard.Richard.Richard.Ri'}
- {icon: 'envelope', link: 'mailto:a28283878@gmail.com'}
- {icon: 'github', link: 'https://github.com/a28283878'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
